# Generated by Django 6.0.2 on 2026-02-06 13:11

from django.db import migrations
from django.db import models


def create_sample_data(apps, schema_editor):
    Profile = apps.get_model('portfolio', 'Profile')
    Project = apps.get_model('portfolio', 'Project')
    Skill = apps.get_model('portfolio', 'Skill')
    Role = apps.get_model('portfolio', 'Role')
    Certification = apps.get_model('portfolio', 'Certification')
    
    # Create Profile
    profile = Profile.objects.create(
        full_name="Sameer Dhakal",
        title="Full Stack Developer",
        bio="Passionate developer with expertise in Django, Python, and modern web technologies.",
        about="I'm a full stack developer with 3+ years of experience building web applications. I love creating elegant solutions to complex problems and am always eager to learn new technologies.",
        email="sameerdhakal1234@gmail.com",
        linkedin="https://linkedin.com/in/sameerdhakal",
        github="https://github.com/dhakalsameer"
    )
    
    # Create Roles
    roles = [
        Role.objects.create(title="Full Stack Developer"),
        Role.objects.create(title="Python Developer"),
        Role.objects.create(title="Django Expert")
    ]
    
    # Create Skills
    skills = [
        Skill.objects.create(name="Python"),
        Skill.objects.create(name="Django"),
        Skill.objects.create(name="JavaScript"),
        Skill.objects.create(name="React"),
        Skill.objects.create(name="PostgreSQL"),
        Skill.objects.create(name="Docker")
    ]
    
    # Create Projects
    Project.objects.create(
        title="E-Commerce Platform",
        description="A full-featured e-commerce platform built with Django and React. Includes user authentication, payment processing, and admin dashboard.",
        tech_stack="Django, React, PostgreSQL, Stripe",
        github_link="https://github.com/dhakalsameer/ecommerce",
        live_link="https://demo-ecommerce.com"
    )
    
    Project.objects.create(
        title="Task Management App",
        description="A collaborative task management application with real-time updates, drag-and-drop interface, and team collaboration features.",
        tech_stack="Django, WebSocket, JavaScript",
        github_link="https://github.com/dhakalsameer/taskmanager"
    )
    
    Project.objects.create(
        title="Blog Platform",
        description="A modern blogging platform with markdown support, comment system, and SEO optimization.",
        tech_stack="Django, PostgreSQL, Bootstrap",
        github_link="https://github.com/dhakalsameer/blogplatform"
    )
    
    # Create Certifications
    Certification.objects.create(
        title="Django Web Framework",
        description="Advanced Django development including REST APIs, authentication, and deployment.",
        issuer="Coursera",
        date_awarded="2024-01-15",
        certificate_url="https://coursera.org/verify/django-cert"
    )
    
    Certification.objects.create(
        title="Python Programming",
        description="Comprehensive Python programming course covering data structures, algorithms, and best practices.",
        issuer="Udemy",
        date_awarded="2023-12-01",
        certificate_url="https://udemy.com/certificate/python-cert"
    )


def delete_sample_data(apps, schema_editor):
    Profile = apps.get_model('portfolio', 'Profile')
    Project = apps.get_model('portfolio', 'Project')
    Skill = apps.get_model('portfolio', 'Skill')
    Role = apps.get_model('portfolio', 'Role')
    Certification = apps.get_model('portfolio', 'Certification')
    
    Profile.objects.all().delete()
    Project.objects.all().delete()
    Skill.objects.all().delete()
    Role.objects.all().delete()
    Certification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_profile_profilephoto_role_skill_and_more'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, delete_sample_data),
    ]

    
